apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: cluster.local-dev
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: andreas@roughedge.se
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: cluster.local-dev
    # Enable HTTP01 validations
    http01: {}