apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  labels:
    svc: nginx-ingress
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-ingress