apiVersion: v1
kind: Service
metadata:
  name: app-nginx-port
  labels:
    svc: app-nginx-port
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    pod: app-nginx
---
apiVersion: v1
kind: Pod
metadata:
    name: app-nginx
    labels:
        pod: app-nginx
spec:
    containers:
    - name: nginx
      image: nginxdemos/hello
      ports:
      - containerPort: 80
