apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ing-nginx
  labels:
    ing: ing-nginx
# annotations:
#    certmanager.k8s.io/cluster-issuer: scriptninjas-dev
spec:
  rules:
  - host: cluster.scriptninjas.se
    http:
      paths:
      - path: /
        backend:
          serviceName: svc-nginx
          servicePort: 80
  # tls:
  #   - hosts:
  #     - cluster.scriptninjas.se
  #     secretName: scriptninjas-dev
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  labels:
    svc: svc-nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    pod: app-nginx
---
apiVersion: v1
kind: Pod
metadata:
    name: app-nginx
    labels:
        pod: app-nginx
spec:
    containers:
    - name: nginx
      image: nginxdemos/hello
      ports:
      - containerPort: 80
